version: 2

python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt
    - requirements: requirements.txt

# The only extra format to build is PDF
formats: [pdf]
