version: 2

python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - sphinx==1.8.4
    - requirements: docs/requirements.txt
    - requirements: requirements.txt
  system_packages: true

# The only extra format to build is PDF
formats: [pdf]
