language: python
cache:
  pip: true
  directories:
    - $HOME/.cache/qnm/
    - $HOME/.qnm/
sudo: required
dist: xenial
branches:
  only:
    - master
    - testing
python:
  - "2.7"
  - "3.6"
  - "3.7"
install:  # install your package and requirements
  - pip install --upgrade pip
  - pip install -r requirements.txt
  # install packages for testing
  - pip install pytest
  # build the qnm package
  - pip install -e .
script:
  # run the test script
  - travis_wait 30 pytest -v
